name: Summerhill Farm
favicon: null
layout_spectrum: 0.89194
typography_spectrum: 0.23819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16151a'
    - '#ecf0f3'
    - '#1f4782'
    - '#9e91a3'
    - '#711119'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5868825556244701
  rhythmicContrast: 0.75
purpose: []
