name: Summerhill Farm
favicon: null
layout_spectrum: 0.04571
typography_spectrum: 0.36356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f4f7'
    - '#141318'
    - '#57668f'
    - '#b39cb6'
    - '#a7101f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5868825556244701
  rhythmicContrast: 0.75
purpose: []
